### PR TITLE
Initial development with README and tests

### PR DESCRIPTION
**Pull request by ako977**
Not intended to have the entire codebase reviewed, but maybe just the eslintrc, README, .gitignore, LICENSE, and package.json, etc. to see if it is good and follows gradealabs standards (or close enough)

### CODE REVIEW

**Comment by dschnare** [comment]
I use MIT. https://tldrlegal.com/license/mit-license

**Comment by dschnare** [comment]
What would we want in a license for our open source software? I *think* MIT sounds good. The consumer of the code can use it any way the choose and we're not liable if the code causes any damages. Is there anything else we'd like in the license?

**Comment by dschnare** [comment]
Jesse suggested using the BSD, and after looking at the breakdown of that license I *think* that might be the better one to use: https://tldrlegal.com/license/bsd-0-clause-license.

Mind you this is the 0BD license.

Consumers don't have to include the license and they can include the original source code in their project.

**Comment by ako977** [comment]
Ok sounds good

**Pull request merged**
